# Generated by Django 6.0.2 on 2026-02-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_branch_name_staff_branchinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchinventory',
            name='low_stock_threshold',
            field=models.FloatField(default=10),
        ),
    ]
