# Generated by Django 6.0.2 on 2026-02-25 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='calories_per_unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='stock_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='pcs', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitemingredient',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitemingredient_set', to='menu.menuitem'),
        ),
    ]
