# Generated by Django 6.0.2 on 2026-02-25 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_supplier_ingredient_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='branch',
        ),
    ]
